server:
  port: 8800
spring:
  redis:
    database: 1 #Redis数据库索引[0,15]，默认0
    host: 127.0.0.1
    port: 6399
    jedis:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: -1 #连接池最大阻塞时间(负值表示没有限制)
        max-idle: 8 #连接池中最大空闲连接
        min-idle: 0 #连接池中最小空闲连接
    timeout: 1000 #连接超时时间
    password: thisispwd

